// Browser regression against the real frontend with isolated API fixtures.
// Run from the repository root with the app serving on localhost:8765.
// Requires the existing mobile-prototype Playwright installation.
const {chromium, expect} = require(process.cwd() + '/mobile-prototype/node_modules/@playwright/test');
(async()=>{
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const assetCache = new Map();
const pendingAssets = [];
page.on("response", response => { if (/unpkg.com|cdn.jsdelivr.net/.test(response.url()) && response.ok()) pendingAssets.push(response.body().then(body => assetCache.set(response.url(), body)).catch(() => {})); });
page.setDefaultTimeout(15000);
const errors=[]; page.on('pageerror', e=>errors.push(e.message));
await page.goto('http://localhost:8765',{waitUntil:'domcontentloaded'});
await expect(page.getByRole('heading',{name:/让下一段旅程，\s*清晰起来。/})).toBeVisible({timeout:30000});
await page.getByRole('textbox',{name:'描述旅行想法'}).fill('南京三天，喜欢历史');
await expect(page.getByRole('textbox',{name:'描述旅行想法'})).toHaveValue('南京三天，喜欢历史');
await page.screenshot({path:'/tmp/studio-home.png',animations:'disabled',timeout:15000});
if(!(await page.locator('.dashboard-composer').evaluate(node=>getComputedStyle(node).backdropFilter)).includes('blur'))throw Error('Glass material missing');
const headerAppearance = () => [...document.querySelectorAll('.topbar,.brand-name')].map(node=>{const s=getComputedStyle(node);return [s.backgroundColor,s.fontSize,s.height,s.color];});
const homeHeaderAppearance=await page.evaluate(headerAppearance);
await Promise.all(pendingAssets);
await page.route(/unpkg.com|cdn.jsdelivr.net/, route => { const body=assetCache.get(route.request().url()); return body ? route.fulfill({contentType:'application/javascript',body}) : route.continue(); });
const raw={destination:'南京',days_count:2,start_date:'2026-09-08',end_date:'2026-09-09',preferences:{attraction:['历史古迹']},days:[{day:1,theme:'古都漫游',timeline:[{type:'attraction',name:'南京博物院',start_time:'09:00',end_time:'12:00',address:'中山东路321号',tip:'提前预约，带好证件。',rating:4.8},{type:'lunch',name:'本地面馆',address:'中山东路',reason:'午间补充能量'}]},{day:2,theme:'秦淮慢游',timeline:[{type:'attraction',name:'夫子庙',start_time:'10:00',end_time:'12:00'}]}],hotel:'测试酒店',notes:'带相机'};
const conversation={id:'c1',title:'南京旅行对话',status:'active',updated_at:'2026-09-05T08:00:00Z'};
const messages=[{id:'m1',conversation_id:'c1',role:'user',content:'想去南京旅行',sequence:1},{id:'m2',conversation_id:'c1',role:'assistant',content:'已经整理好南京行程。\\n可以继续调整景点。',sequence:2,artifacts:[{type:'itinerary_collection',items:[{itinerary_id:'p1',destination:'南京',duration_days:2}]}]}];
const requests=[];
let scenario = "normal";
let failSave = false;
let failTips = false;
await page.route('**/api/**',async route=>{
 const req=route.request(), u=new URL(req.url()), path=u.pathname; requests.push({path,method:req.method(),body:req.postDataJSON()});
 let data={};
 if(path==='/api/auth/login')data={token:'fixture',username:'测试旅行者'};
 else if(path==='/api/profile')data={revision:1,trip_count:1,active_facts:[{id:'f1',category:'travel_pace',value_text:'喜欢慢旅行',polarity:'prefer',scope_type:'global',scope_key:{},source_kind:'manual'}],candidate_facts:[]};
 else if(path==='/api/history')data={items:[{id:'p1',destination:'南京',days_count:2,start_date:raw.start_date,end_date:raw.end_date}],next_cursor:null};
 else if(path==='/api/history/p1')data={plan:raw};
 else if(path.includes('/tips/stream'))return route.fulfill({contentType:'text/event-stream',body:''});
 else if(path==='/api/conversations')data=req.method()==='POST'?conversation:[conversation];
 else if(path.endsWith('/messages'))data=req.method()==='POST'?{message:{id:'m3',role:'user',content:req.postDataJSON().content,sequence:3},run:{id:'r1',kind:'chat',conversation_id:'c1',status:'queued'}}:messages;
 else if(path.endsWith('/planning-brief'))data=null;
 else if(path.endsWith('/view'))data=conversation;
 else if(path==='/api/runs')data=['waiting_user','failed','running'].includes(scenario)?[{id:'r1',kind:'chat',conversation_id:'c1',status:scenario,pending_interaction:scenario==='waiting_user'?{interaction_id:'i1',prompt:'两个景点都换吗？'}:null,error_public:{message:'暂时无法生成',retryable:true}}]:[];
 else if(path.endsWith('/events'))data=[];
 else if(path.endsWith('/resume')||path.endsWith('/retry')||path.endsWith('/cancel')){data={id:'r1',kind:'chat',conversation_id:'c1',status:path.endsWith('/cancel')?'cancelled':'queued'}; scenario='normal';}
 else if(path==='/api/runs/r1/stream'&&scenario!=='normal')return route.fulfill({contentType:'text/event-stream',body:''});
 else if(path==='/api/runs/r1/stream')return route.fulfill({contentType:'text/event-stream',body:'id: 1\nevent: custom\ndata: {"kind":"run.status","status":"succeeded"}\n\n'});
 else if(path==='/api/runs/r1')data={id:'r1',status:'succeeded',result_itinerary_id:'p1'};
 else if(path==='/api/config')data={};
 else if(path.includes('/timeline')) { if(failSave) return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'保存暂时失败，请重试'})}); data={plan:raw}; }
 else if(path==='/api/history/p1/tips'&&failTips) return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'贴士服务暂不可用'})});
 else if(path.includes('/poi/search'))data={results:[{name:'玄武湖',address:'玄武区',rating:4.7}]};
 return route.fulfill({contentType:'application/json',body:JSON.stringify(data)});
});
await page.evaluate(()=>localStorage.setItem('auth',JSON.stringify({username:'测试旅行者',token:'fixture'})));
await page.goto('http://localhost:8765/?view_plan_id=p1',{waitUntil:'domcontentloaded'});
await expect(page.getByRole('heading',{name:'南京 · 2日游'})).toBeVisible({timeout:30000});
await expect(page.getByText('想去南京旅行',{exact:true})).toBeVisible();
await page.getByRole('button',{name:'历史对话',exact:true}).click();
await expect(page.getByRole('button',{name:'南京旅行对话',exact:true})).toBeVisible();
await page.getByRole('button',{name:'关闭历史对话'}).click();
await page.getByRole('combobox',{name:'给途见发送消息'}).fill('第二天轻松一点');
await page.getByRole('button',{name:'发送消息',exact:true}).click();
await expect.poll(()=>requests.filter(r=>r.method==='POST'&&r.path.endsWith('/messages')).length).toBe(1);
if(requests.find(r=>r.method==='POST'&&r.path.endsWith('/messages')).body.related_itinerary_id!=='p1')throw Error('Missing itinerary context');
await expect(page.getByRole('button',{name:'查看南京 · 2日 · 日期未定 · V1完整方案'})).toBeVisible();
await page.screenshot({path:'/tmp/studio-detail.png'});
await expect(page.locator('.topbar')).toHaveCount(1);
for(const selector of ['.topbar','.chat-header','.sl-detail-header']) if(await page.locator(selector).evaluate(node=>getComputedStyle(node).borderBottomWidth)!=='0px')throw Error(`Unexpected divider: ${selector}`);
if(JSON.stringify(await page.evaluate(headerAppearance))!==JSON.stringify(homeHeaderAppearance))throw Error('Navigation appearance differs between pages');
await expect(page.locator('.rd-top-nav')).toHaveCount(0);
await expect(page.locator('.topnav').getByRole('button')).toHaveCount(2);
await expect(page.locator('.topnav-link.active')).toHaveText('旅行工作区');
await page.getByRole('button',{name:'打开我的旅行画像',exact:true}).click();
await expect(page.getByRole('dialog',{name:'我的旅行画像'})).toBeVisible();
await expect(page.getByText('喜欢慢旅行',{exact:true})).toBeVisible();
await page.getByRole('dialog').getByRole('button',{name:'编辑',exact:true}).click();
await page.locator('.memory-inline-edit input').fill('喜欢轻松慢游');
await page.locator('.memory-inline-edit').getByRole('button',{name:'保存',exact:true}).click();
await expect.poll(()=>requests.some(r=>r.method==='PATCH'&&r.path==='/api/memories/f1')).toBe(true);
await page.keyboard.press('Escape');
await expect(page.getByRole('dialog',{name:'我的旅行画像'})).toHaveCount(0);
// The default header is compact and never dismounts the map during disclosure.
const headerHeight=await page.locator('.sl-detail-header').evaluate(node=>node.getBoundingClientRect().height);
if(headerHeight<140||headerHeight>195)throw Error(`Header height ${headerHeight}`);
await page.locator('.rd-map-column .map-frame').evaluate(node=>node.dataset.retained='yes');
await page.getByRole('button',{name:'行程概览',exact:true}).click();
await expect(page.locator('.sl-overview')).toBeVisible();
await page.getByRole('button',{name:'行程概览',exact:true}).click();
await expect(page.locator('.sl-overview')).toHaveCount(0);
await page.getByRole('button',{name:'查看南京博物院',exact:true}).click();
await expect(page.getByRole('region',{name:'南京博物院',exact:true})).toBeVisible();
await expect(page.locator('.sl-drawer').getByText('开放时间',{exact:true})).toBeVisible();
await page.screenshot({path:'/tmp/studio-drawer.png'});
failTips=true;
await page.getByRole('button',{name:'重新生成景点贴士',exact:true}).click();
await expect(page.getByRole('button',{name:'重试生成贴士',exact:true})).toBeVisible();
failTips=false;
await page.getByRole('button',{name:'重试生成贴士',exact:true}).click();
await page.keyboard.press('Escape');
await expect(page.locator('.sl-drawer')).toBeHidden();
await page.getByRole('button',{name:'旅行资料',exact:true}).click();
await page.getByRole('textbox',{name:'旅行备注',exact:true}).fill('未保存的资料草稿');
await page.keyboard.press('Escape');
await page.getByRole('button',{name:'旅行资料',exact:true}).click();
await expect(page.getByRole('textbox',{name:'旅行备注',exact:true})).toHaveValue('未保存的资料草稿');
await page.getByRole('button',{name:'保存住宿与备注',exact:true}).click();
await expect.poll(()=>requests.some(r=>r.path.endsWith('/metadata')&&r.body.notes==='未保存的资料草稿')).toBe(true);
await page.keyboard.press('Escape');
await page.getByRole('button',{name:'编辑行程',exact:true}).click();
await expect(page.locator('.sl-edit-actions')).toHaveCount(1);
await expect(page.getByRole('button',{name:'编辑行程',exact:true})).toHaveCount(0);
await page.locator('.studio-editor input[type=time]').first().fill('10:15');
await page.locator('.studio-editor input[type=time]').first().blur();
await page.getByRole('tab',{name:/Day 2/}).click();
await expect(page.locator('.studio-editor input[type=time]').first()).toHaveValue('10:00');
await page.getByRole('tab',{name:/Day 1/}).click();
await expect(page.locator('.studio-editor input[type=time]').first()).toHaveValue('10:15');
await page.getByRole('button',{name:'撤销修改',exact:true}).click();
await expect(page.locator('.studio-editor input[type=time]').first()).toHaveValue('09:00');
await page.getByRole('button',{name:'重做修改',exact:true}).click();
await expect(page.locator('.studio-editor input[type=time]').first()).toHaveValue('10:15');
page.once('dialog',dialog=>dialog.dismiss());
await page.getByRole('button',{name:'取消',exact:true}).click();
await expect(page.locator('.studio-editor')).toBeVisible();
// A rejected history navigation must leave the conversation and draft untouched.
await page.getByRole('button',{name:'历史对话',exact:true}).click();
page.once('dialog',dialog=>dialog.dismiss());
await page.getByRole('button',{name:'南京旅行对话',exact:true}).click();
await expect(page.locator('.studio-editor input[type=time]').first()).toHaveValue('10:15');
await page.getByRole('button',{name:'关闭历史对话'}).click();
await page.getByRole('button',{name:'更换',exact:false}).first().click();
await expect(page.locator('.sl-drawer')).toBeVisible();
await expect(page.locator('.sl-edit-actions')).toHaveCount(1);
await page.getByRole('textbox',{name:'搜索地点',exact:true}).fill('玄武湖');
await page.getByRole('button',{name:'搜索',exact:true}).click();
await page.locator('.sl-poi-result').click();
await expect(page.locator('.studio-editor').getByText('玄武湖',{exact:true})).toBeVisible();
await expect(page.locator('.sl-drawer')).toBeHidden();
await page.getByRole('button',{name:'撤销修改',exact:true}).click();
await expect(page.locator('.studio-editor').getByText('南京博物院',{exact:true})).toBeVisible();
failSave=true;
await page.getByRole('button',{name:'完成编辑',exact:true}).click();
await expect(page.getByText('保存暂时失败，请重试',{exact:true})).toBeVisible();
await expect(page.locator('.studio-editor input[type=time]').first()).toHaveValue('10:15');
await page.screenshot({path:'/tmp/studio-editing.png'});
failSave=false;
await page.getByRole('button',{name:'完成编辑',exact:true}).click();
await expect(page.locator('.studio-editor')).toHaveCount(0);
const savedRequests=requests.filter(r=>r.path.includes('/timeline'));
if(savedRequests.at(-1).body.days[0].timeline[0].start_time!=='10:15')throw Error('Draft lost on save');
await page.getByRole('button',{name:'编辑行程',exact:true}).click();
await page.locator('.studio-editor input[type=time]').first().fill('10:30');
await page.locator('.studio-editor input[type=time]').first().blur();
page.once('dialog',dialog=>dialog.accept());
await page.getByRole('button',{name:'取消',exact:true}).click();
await expect(page.locator('.studio-editor')).toHaveCount(0);
if(await page.locator('.rd-map-column .map-frame').getAttribute('data-retained')!=='yes')throw Error('Map remounted');
for(const width of [1024,1440]) {
 await page.setViewportSize({width,height:1000});
 const boxes=await page.locator('.sl-detail-body').evaluate(node=>[...node.children].map(child=>{const r=child.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width};}));
 await page.screenshot({path:`/tmp/studio-workspace-${width}.png`});
 if(Math.abs(boxes[0].y-boxes[1].y)>1||boxes[1].x<=boxes[0].x||boxes.some(box=>box.width<=0))throw Error('Route and map no longer side by side');
}
await page.setViewportSize({width:390,height:844});
await page.getByRole('navigation',{name:'工作区视图'}).getByRole('button',{name:'行程',exact:true}).click();
await page.getByRole('heading',{name:'南京 · 2日游'}).scrollIntoViewIfNeeded();
await expect(page.getByRole('heading',{name:'南京 · 2日游'})).toBeVisible();
await page.getByRole('button',{name:'查看南京博物院',exact:true}).click();
await expect(page.locator('.sl-drawer')).toBeVisible();
const drawerHit = await page.locator('.sl-drawer h3').evaluate(node=>{const r=node.getBoundingClientRect();return node.closest('.sl-drawer').contains(document.elementFromPoint(r.x+5,r.y+5));});
if(!drawerHit)throw Error('Drawer is covered by route content');
await page.screenshot({path:'/tmp/studio-mobile-drawer.png'});
await page.keyboard.press('Escape');
await page.screenshot({path:'/tmp/studio-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2))throw Error('Mobile horizontal overflow');
for (const width of [768,390]) {
 await page.setViewportSize({width,height:900});
 const workspaceNav=page.getByRole('navigation',{name:'工作区视图'});
 const detailNav=page.getByRole('navigation',{name:'行程视图'});
 await workspaceNav.getByRole('button',{name:'对话',exact:true}).click();
 const composer=page.getByRole('combobox',{name:'给途见发送消息'});
 await composer.fill('手机切换保留草稿');
 await workspaceNav.getByRole('button',{name:'行程',exact:true}).click();
 await detailNav.getByRole('button',{name:'地图',exact:true}).click();
 await expect(page.locator('.rd-map-column .map-frame')).toBeVisible();
 await page.screenshot({path:`/tmp/studio-map-${width}.png`});
 await detailNav.getByRole('button',{name:'路线',exact:true}).click();
 await page.getByRole('button',{name:'编辑行程',exact:true}).click();
 await page.locator('.studio-editor input[type=time]').first().fill('10:45');
 await page.locator('.studio-editor input[type=time]').first().blur();
 await detailNav.getByRole('button',{name:'地图',exact:true}).click();
 await workspaceNav.getByRole('button',{name:'对话',exact:true}).click();
 await expect(composer).toHaveValue('手机切换保留草稿');
 await workspaceNav.getByRole('button',{name:'行程',exact:true}).click();
 await detailNav.getByRole('button',{name:'路线',exact:true}).click();
 await expect(page.locator('.studio-editor input[type=time]').first()).toHaveValue('10:45');
 await page.screenshot({path:`/tmp/studio-editing-${width}.png`});
 page.once('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'取消',exact:true}).click();
 if(await page.locator('.rd-map-column .map-frame').getAttribute('data-retained')!=='yes')throw Error('Map remounted during mobile navigation');
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2))throw Error(`Horizontal overflow ${width}`);
 await page.screenshot({path:`/tmp/studio-itinerary-${width}.png`});
 await page.getByRole('button',{name:'打开我的旅行画像',exact:true}).click();
 await expect(page.getByText('喜欢慢旅行',{exact:true})).toBeVisible();
 await page.screenshot({path:`/tmp/studio-profile-${width}.png`});
 await page.keyboard.press('Escape');
}
await page.setViewportSize({width:1440,height:1000});
await page.getByRole('button',{name:'返回首页'}).click();
await expect(page.locator('.topnav-link.active')).toHaveText('首页');
await page.getByRole('button',{name:'打开我的旅行画像',exact:true}).click();
await expect(page.getByRole('dialog',{name:'我的旅行画像'})).toBeVisible();
await page.keyboard.press('Escape');
await page.getByRole('textbox',{name:'描述旅行想法'}).fill('苏州两天');
await page.getByRole('button',{name:'开始旅行规划',exact:true}).click();
await expect.poll(()=>requests.filter(r=>r.method==='POST'&&r.path.endsWith('/messages')).length).toBe(2);
await expect(page.getByText('苏州两天',{exact:true})).toBeVisible();
for(const next of ['waiting_user','failed','running']) {
 scenario=next;
 await page.goto('http://localhost:8765/?view_plan_id=p1',{waitUntil:'domcontentloaded'});
 await expect(page.getByRole('heading',{name:'南京 · 2日游'})).toBeVisible({timeout:30000});
 if(next==='waiting_user'){
   await page.getByRole('textbox',{name:'填写补充信息'}).fill('两个都换，推荐历史景点');
   await page.getByRole('button',{name:'提交并继续',exact:true}).click();
   await expect.poll(()=>requests.some(r=>r.path.endsWith('/resume')&&r.body.interaction_id==='i1')).toBe(true);
 }else if(next==='failed'){
   await page.getByRole('button',{name:'重试这条消息'}).click();
   await expect.poll(()=>requests.some(r=>r.path.endsWith('/retry'))).toBe(true);
 }else{
   await page.getByRole('button',{name:'停止当前任务',exact:true}).click();
   await expect.poll(()=>requests.some(r=>r.path.endsWith('/cancel'))).toBe(true);
 }
}
await page.evaluate(()=>localStorage.removeItem('auth'));
await page.goto('http://localhost:8765',{waitUntil:'domcontentloaded'});
await expect(page.getByRole('textbox',{name:'描述旅行想法'})).toBeVisible();
for(const width of [1440,1024,768,390]) {
 await page.setViewportSize({width,height:1000});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2))throw Error(`Home overflow ${width}`);
 await page.screenshot({path:`/tmp/studio-home-${width}.png`,fullPage:true});
}
await page.getByRole('button',{name:'南京',exact:true}).click();
await expect(page.getByRole('textbox',{name:'描述旅行想法'})).toBeFocused();
await page.getByRole('textbox',{name:'描述旅行想法'}).fill('登录前的南京三日计划');
const sentBeforeLogin=requests.filter(r=>r.method==='POST'&&r.path.endsWith('/messages')).length;
await page.getByRole('button',{name:'开始旅行规划',exact:true}).click();
const login=page.getByRole('dialog',{name:'登录或注册途见'});
await expect(login).toBeVisible();
await page.keyboard.press('Escape');
await expect(login).toHaveCount(0);
await expect(page.getByRole('button',{name:'开始旅行规划',exact:true})).toBeFocused();
await expect(page.getByRole('textbox',{name:'描述旅行想法'})).toHaveValue('登录前的南京三日计划');
await page.getByRole('button',{name:'开始旅行规划',exact:true}).click();
await page.screenshot({path:'/tmp/studio-auth-mobile.png'});
await login.getByLabel('用户名',{exact:true}).fill('测试旅行者');
await login.getByLabel('密码',{exact:true}).fill('isolated-test-password');
await login.locator('.form-submit').focus();
await page.keyboard.press('Tab');
await expect(login.getByRole('button',{name:'关闭登录窗口'})).toBeFocused();
await login.locator('.form-submit').click();
await expect.poll(()=>requests.filter(r=>r.method==='POST'&&r.path.endsWith('/messages')).length).toBe(sentBeforeLogin+1);
if(requests.filter(r=>r.method==='POST'&&r.path.endsWith('/messages')).at(-1).body.content!=='登录前的南京三日计划')throw Error('Login lost draft');
await page.getByRole('navigation',{name:'工作区视图'}).getByRole('button',{name:'对话',exact:true}).click();
await expect(page.getByRole('combobox',{name:'给途见发送消息'})).toBeVisible();
await page.screenshot({path:'/tmp/studio-chat-mobile.png'});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);
if(overflow)throw Error('Mobile horizontal overflow');
if(errors.length)throw Error(errors.join('\n'));
console.log('PASS: homepage input, history restoration, contextual send, result detail, live profile modal, manual save, mobile overflow, single home submission, profile edit, waiting-user resume, retry and cancel, compact header, parallel layout, drawer disclosure, draft retention, undo/redo, discard guard, save failure/retry, tip retry, retained map; no page errors');
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
